name: task_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  bcrypt: ^1.1.3
  camera: ^0.11.3
  crypto: ^3.0.7
  csv: ^6.0.0
  dart_jsonwebtoken: ^3.3.1
  excel: ^4.0.6
  fl_chart: ^1.1.1
  flutter:
    sdk: flutter
  geolocator: ^14.0.2
  google_maps_flutter: ^2.14.0
  http: ^1.6.0
  image_picker: ^1.2.1
  intl: ^0.20.2
  month_picker_dialog: ^6.7.0
  month_selector: ^1.0.2
  mysql1: ^0.20.0
  open_file: ^3.5.10
  path_provider: ^2.1.5
  pdf: ^3.11.3
  permission_handler: ^12.0.1
  shared_preferences: ^2.5.3
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  syncfusion_flutter_xlsio: ^29.2.11
  url_launcher: ^6.3.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/com_logo.png
    - assets/bac.jpeg
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.otf
        - asset: assets/fonts/Inter-Medium.otf
        - asset: assets/fonts/Inter-SemiBold.otf
        - asset: assets/fonts/Inter-Bold.otf