name: backend
description: Dart backend for Railway
version: 1.0.0

environment:
  sdk: ^3.0.0

dependencies:
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  mysql1: ^0.20.0
  bcrypt: ^1.1.3
  dart_jsonwebtoken: ^3.3.1
  pool: ^1.5.1
  crypto: ^3.0.7
  csv: ^6.0.0
  intl: ^0.20.2

dev_dependencies:
  lints: ^5.0.0
rm -rf .dart_toolrm -rf .dart_tool